# Generated by Django 3.0.7 on 2020-12-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dba', '0003_user_objid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='objid',
            field=models.BinaryField(default=False, max_length=100),
        ),
    ]
